name: 'shopify'
version: '0.19.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
profile: 'wow_ai_transformation'

quoting:
  database: true
  schema: true
  identifier: true

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS `{{ target.project }}.{{ target.dataset }}_stg_shopify` OPTIONS(location='{{ target.location }}')"
  - "CREATE SCHEMA IF NOT EXISTS `{{ target.project }}.{{ target.dataset }}_airshopify` OPTIONS(location='{{ target.location }}')"
  - "CREATE SCHEMA IF NOT EXISTS `{{ target.project }}.{{ target.dataset }}_stg_salla` OPTIONS(location='{{ target.location }}')"
  - "CREATE SCHEMA IF NOT EXISTS `{{ target.project }}.{{ target.dataset }}_airsalla` OPTIONS(location='{{ target.location }}')"
models:
  shopify:
    +materialized: table
    staging:
      +schema: stg_shopify
      +materialized: view
    marts:
      +schema: airshopify
      +materialized: table
    utils:
      +schema: airshopify
      +materialized: table
    intermediate:
      +materialized: ephemeral
      int_shopify__customer_email_rollup:
        +materialized: view # so we can use the dbt_utils.star macro
    salla_staging:
      +schema: stg_salla
      +materialized: view
    salla_marts:
      +schema: airsalla
      +materialized: table
    salla_utils:
      +schema: airsalla
      +materialized: table
    salla_intermediate:
      +materialized: ephemeral
      int_salla__customer_email_rollup:
        +materialized: view
