
name: 'shopify'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=0.18.0", "<0.20.0"]

models: 
  shopify:
    materialized: table
    intermediate:
      materialized: view

vars:
  shopify:
    shopify_customer: "{{ ref('stg_shopify__customer') }}"
    shopify_order: "{{ ref('stg_shopify__order') }}"
    shopify_order_line: "{{ ref('stg_shopify__order_line') }}"
    shopify_order_line_refund: "{{ ref('stg_shopify__order_line_refund') }}"
    shopify_product: "{{ ref('stg_shopify__product') }}"

