name: 'shopify'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  shopify:
    +schema: shopify
    +materialized: table
    rest:
      intermediate:
        +materialized: ephemeral
        int_shopify__customer_email_rollup:
          +materialized: view # so we can use the dbt_utils.star macro
    graphql:
      intermediate:
        +materialized: ephemeral
        int_shopify_gql__customer_email_rollup:
          +materialized: view # so we can use the dbt_utils.star macro
        base:
          +materialized: ephemeral
          int_shopify_gql__customer:
            +materialized: view # so we can use the dbt_utils.star and dbt_utils.get_column_values macros
          int_shopify_gql__collection:
            +materialized: view # so we can use the dbt_utils.star and dbt_utils.get_column_values macros
          int_shopify_gql__order:
            +materialized: view # so we can use the dbt_utils.star and dbt_utils.get_column_values macros
          int_shopify_gql__product_variant:
            +materialized: view # so we can use the dbt_utils.star and dbt_utils.get_column_values macros
    staging:
      +schema: shopify_source
      +materialized: view

vars:
  shopify:
    shopify_customer: "{{ source('shopify', 'customer') }}"
    shopify_order: "{{ source('shopify', 'order') }}"
    shopify_order_line: "{{ source('shopify', 'order_line') }}"
    shopify_order_line_refund: "{{ source('shopify', 'order_line_refund') }}"
    shopify_product: "{{ source('shopify', 'product') }}"
    shopify_product_variant: "{{ source('shopify', 'product_variant') }}"
    shopify_transaction: "{{ source('shopify', 'transaction') }}"
    shopify_refund: "{{ source('shopify', 'refund') }}"
    shopify_order_adjustment: "{{ source('shopify', 'order_adjustment') }}"
    shopify_abandoned_checkout: "{{ source('shopify', 'abandoned_checkout') }}"
    shopify_collection_product: "{{ source('shopify', 'collection_product') }}"
    shopify_collection: "{{ source('shopify', 'collection') }}"
    shopify_customer_tag: "{{ source('shopify', 'customer_tag') }}"    
    shopify_discount_allocation: "{{ source('shopify', 'discount_allocation') }}" 
    shopify_discount_application: "{{ source('shopify', 'discount_application') }}" 
    shopify_discount_code_app: "{{ source('shopify', 'discount_code_app') }}" 
    shopify_discount_code_basic: "{{ source('shopify', 'discount_code_basic') }}" 
    shopify_discount_code_bxgy: "{{ source('shopify', 'discount_code_bxgy') }}" 
    shopify_discount_code_free_shipping: "{{ source('shopify', 'discount_code_free_shipping') }}" 
    shopify_discount_redeem_code: "{{ source('shopify', 'discount_redeem_code') }}"         
    shopify_fulfillment: "{{ source('shopify', 'fulfillment') }}"
    shopify_inventory_item: "{{ source('shopify', 'inventory_item') }}"
    shopify_inventory_level: "{{ source('shopify', 'inventory_level') }}"
    shopify_inventory_quantity: "{{ source('shopify', 'inventory_quantity') }}"
    shopify_location: "{{ source('shopify', 'location') }}"
    shopify_media: "{{ source('shopify', 'media') }}"
    shopify_media_image: "{{ source('shopify', 'media_image') }}"    
    shopify_metafield: "{{ source('shopify', 'metafield') }}"
    shopify_order_note_attribute: "{{ source('shopify', 'order_note_attribute') }}"
    shopify_order_shipping_line: "{{ source('shopify', 'order_shipping_line') }}"
    shopify_order_shipping_tax_line: "{{ source('shopify', 'order_shipping_tax_line') }}"
    shopify_order_tag: "{{ source('shopify', 'order_tag') }}"
    shopify_order_url_tag: "{{ source('shopify', 'order_url_tag') }}"
    shopify_product_media: "{{ source('shopify', 'product_media') }}"
    shopify_product_variant_media: "{{ source('shopify', 'product_variant_media') }}"
    shopify_product_tag: "{{ source('shopify', 'product_tag') }}"
    shopify_shop: "{{ source('shopify', 'shop') }}"
    shopify_tax_line: "{{ source('shopify', 'tax_line') }}"
    shopify_tender_transaction: "{{ source('shopify', 'tender_transaction') }}"
    shopify_abandoned_checkout_discount_code: "{{ source('shopify', 'abandoned_checkout_discount_code') }}"
    shopify_order_discount_code: "{{ source('shopify', 'order_discount_code') }}"
    shopify_abandoned_checkout_shipping_line: "{{ source('shopify', 'abandoned_checkout_shipping_line') }}"
    shopify_fulfillment_event: "{{ source('shopify', 'fulfillment_event') }}"

    shopify_gql_customer: "{{ source('shopify_graphql', 'customer') }}"
    shopify_gql_order: "{{ source('shopify_graphql', 'order') }}"
    shopify_gql_order_line: "{{ source('shopify_graphql', 'order_line') }}"
    shopify_gql_order_line_refund: "{{ source('shopify_graphql', 'order_line_refund') }}"
    shopify_gql_product: "{{ source('shopify_graphql', 'product') }}"
    shopify_gql_product_variant: "{{ source('shopify_graphql', 'product_variant') }}"
    shopify_gql_transaction: "{{ source('shopify_graphql', 'transaction') }}"
    shopify_gql_refund: "{{ source('shopify_graphql', 'refund') }}"
    shopify_gql_order_adjustment: "{{ source('shopify_graphql', 'order_adjustment') }}"
    shopify_gql_abandoned_checkout: "{{ source('shopify_graphql', 'abandoned_checkout') }}"
    shopify_gql_collection_product: "{{ source('shopify_graphql', 'collection_product') }}"
    shopify_gql_collection: "{{ source('shopify_graphql', 'collection') }}"
    shopify_gql_collection_rule: "{{ source('shopify_graphql', 'collection_rule') }}"
    shopify_gql_customer_address: "{{ source('shopify_graphql', 'customer_address') }}"
    shopify_gql_customer_tag: "{{ source('shopify_graphql', 'customer_tag') }}"    
    shopify_gql_customer_visit: "{{ source('shopify_graphql', 'customer_visit') }}"
    shopify_gql_discount_allocation: "{{ source('shopify_graphql', 'discount_allocation') }}" 
    shopify_gql_discount_application: "{{ source('shopify_graphql', 'discount_application') }}" 
    shopify_gql_discount_code_app: "{{ source('shopify_graphql', 'discount_code_app') }}" 
    shopify_gql_discount_code_basic: "{{ source('shopify_graphql', 'discount_code_basic') }}" 
    shopify_gql_discount_code_bxgy: "{{ source('shopify_graphql', 'discount_code_bxgy') }}" 
    shopify_gql_discount_code_free_shipping: "{{ source('shopify_graphql', 'discount_code_free_shipping') }}" 
    shopify_gql_discount_redeem_code: "{{ source('shopify_graphql', 'discount_redeem_code') }}"         
    shopify_gql_fulfillment: "{{ source('shopify_graphql', 'fulfillment') }}"
    shopify_gql_fulfillment_tracking_info: "{{ source('shopify_graphql', 'fulfillment_tracking_info') }}"
    shopify_gql_inventory_item: "{{ source('shopify_graphql', 'inventory_item') }}"
    shopify_gql_inventory_level: "{{ source('shopify_graphql', 'inventory_level') }}"
    shopify_gql_inventory_quantity: "{{ source('shopify_graphql', 'inventory_quantity') }}"
    shopify_gql_location: "{{ source('shopify_graphql', 'location') }}"
    shopify_gql_media: "{{ source('shopify_graphql', 'media') }}"
    shopify_gql_media_image: "{{ source('shopify_graphql', 'media_image') }}"    
    shopify_gql_metafield: "{{ source('shopify_graphql', 'metafield') }}"
    shopify_gql_order_note_attribute: "{{ source('shopify_graphql', 'order_note_attribute') }}"
    shopify_gql_order_shipping_line: "{{ source('shopify_graphql', 'order_shipping_line') }}"
    shopify_gql_order_shipping_tax_line: "{{ source('shopify_graphql', 'order_shipping_tax_line') }}"
    shopify_gql_order_tag: "{{ source('shopify_graphql', 'order_tag') }}"
    shopify_gql_order_url_tag: "{{ source('shopify_graphql', 'order_url_tag') }}"
    shopify_gql_product_media: "{{ source('shopify_graphql', 'product_media') }}"
    shopify_gql_product_variant_media: "{{ source('shopify_graphql', 'product_variant_media') }}"
    shopify_gql_product_tag: "{{ source('shopify_graphql', 'product_tag') }}"
    shopify_gql_shop: "{{ source('shopify_graphql', 'shop') }}"
    shopify_gql_tax_line: "{{ source('shopify_graphql', 'tax_line') }}"
    shopify_gql_tender_transaction: "{{ source('shopify_graphql', 'tender_transaction') }}"
    shopify_gql_abandoned_checkout_discount_code: "{{ source('shopify_graphql', 'abandoned_checkout_discount_code') }}"
    shopify_gql_order_discount_code: "{{ source('shopify_graphql', 'order_discount_code') }}"
    shopify_gql_abandoned_checkout_shipping_line: "{{ source('shopify_graphql', 'abandoned_checkout_shipping_line') }}"
    shopify_gql_fulfillment_event: "{{ source('shopify_graphql', 'fulfillment_event') }}"
    shopify_gql_fulfillment_order_line_item: "{{ source('shopify_graphql', 'fulfillment_order_line_item') }}"