name: 'shopify'
version: '0.19.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
profile: 'wow_ai_transformation'

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS `{{ target.project }}.{{ target.dataset }}_stg_shopify`"
  - "CREATE SCHEMA IF NOT EXISTS `{{ target.project }}.{{ target.dataset }}_airshopify`"
models:
  shopify:
    +materialized: table
    staging:
      +schema: stg_shopify
      +materialized: view
    marts:
      +schema: airshopify
      +materialized: table
    utils:
      +schema: airshopify
      +materialized: table
    intermediate:
      +materialized: ephemeral
      int_shopify__customer_email_rollup:
        +materialized: view # so we can use the dbt_utils.star macro
