wow_ai_transformation:
  outputs:
    worood_dev:
      dataset: worood_test
      location: EU  # Change to your actual region: EU, us-central1, europe-west1, etc.
      method: oauth
      project: wow-ai-461911
      threads: 4
      type: bigquery
    worood_prod:
      dataset: worood_reports
      location: EU  # Change to your actual region
      method: oauth
      project: wow-ai-461911
      threads: 4
      type: bigquery
    breathe_dev:
      dataset: breathe_test
      location: EU  # Change to your actual region
      method: oauth
      project: wow-ai-461911
      threads: 4
      type: bigquery
    breathe_prod:
      dataset: breathe_reports
      location: EU  # Change to your actual region
      method: oauth
      project: wow-ai-461911
      threads: 4
      type: bigquery
  target: worood_dev
